=== vkirienko/TagTranslit/Mapping/Transliteration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Transliteration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="element" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="from" type="xs:string" use="required"/>
						<xs:attribute name="to" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="title" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== vkirienko/TagTranslit/Mapping/ГОСТ 7.79-2000.xml
<?xml version="1.0" encoding="UTF-8"?>
<Transliteration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Transliteration.xsd" title="ГОСТ 7.79-2000">
	<element from="а" to="a"/>
	<element from="А" to="A"/>
	<element from="б" to="b"/>
	<element from="Б" to="B"/>
	<element from="в" to="v"/>
	<element from="В" to="V"/>
	<element from="г" to="g"/>
	<element from="Г" to="G"/>
	<element from="д" to="d"/>
	<element from="Д" to="D"/>
	<element from="е" to="e"/>
	<element from="Е" to="E"/>
	<element from="ё" to="jo"/>
	<element from="Ё" to="Jo"/>
	<element from="ж" to="zh"/>
	<element from="Ж" to="Zh"/>
	<element from="з" to="z"/>
	<element from="З" to="Z"/>
	<element from="и" to="i"/>
	<element from="И" to="I"/>
	<element from="й" to="jj"/>
	<element from="Й" to="Jj"/>
	<element from="к" to="k"/>
	<element from="К" to="K"/>
	<element from="л" to="l"/>
	<element from="Л" to="L"/>
	<element from="м" to="m"/>
	<element from="М" to="M"/>
	<element from="н" to="n"/>
	<element from="Н" to="N"/>
	<element from="о" to="o"/>
	<element from="О" to="O"/>
	<element from="п" to="p"/>
	<element from="П" to="P"/>
	<element from="р" to="r"/>
	<element from="Р" to="R"/>
	<element from="с" to="s"/>
	<element from="С" to="S"/>
	<element from="т" to="t"/>
	<element from="Т" to="T"/>
	<element from="у" to="u"/>
	<element from="У" to="U"/>
	<element from="ф" to="f"/>
	<element from="Ф" to="F"/>
	<element from="х" to="kh"/>
	<element from="Х" to="Kh"/>
	<element from="ц" to="c"/>
	<element from="Ц" to="C"/>
	<element from="ч" to="ch"/>
	<element from="Ч" to="Ch"/>
	<element from="ш" to="sh"/>
	<element from="Ш" to="Sh"/>
	<element from="щ" to="shh"/>
	<element from="Щ" to="Shh"/>
	<element from="ь" to="'"/>
	<element from="Ь" to="'"/>
	<element from="ы" to="y"/>
	<element from="Ы" to="Y"/>
	<element from="ъ" to="&quot;"/>
	<element from="Ъ" to="&quot;"/>
	<element from="э" to="eh"/>
	<element from="Э" to="Eh"/>
	<element from="ю" to="ju"/>
	<element from="Ю" to="Ju"/>
	<element from="я" to="ja"/>
	<element from="Я" to="Ja"/>
</Transliteration>

=== vkirienko/TagTranslit/Mapping/Глаголица.xml
<?xml version="1.0" encoding="UTF-8"?>
<Transliteration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Transliteration.xsd" title="Глаголица">
	<element from="а" to="Аз"/>
	<element from="А" to="АЗ"/>
	<element from="б" to="Буки"/>
	<element from="Б" to="БУКИ"/>
	<element from="в" to="Веди"/>
	<element from="В" to="ВЕДИ"/>
	<element from="г" to="Глагол"/>
	<element from="Г" to="ГЛАГОЛ"/>
	<element from="д" to="Добро"/>
	<element from="Д" to="ДОБРО"/>
	<element from="е" to="Еси"/>
	<element from="Е" to="ЕСИ"/>
	<element from="ё" to="Он'"/>
	<element from="Ё" to="ОН'"/>
	<element from="ж" to="Живите"/>
	<element from="Ж" to="ЖИВИТЕ"/>
	<element from="з" to="Земля"/>
	<element from="З" to="ЗЕМЛЯ"/>
	<element from="и" to="и"/>
	<element from="И" to="И"/>
	<element from="й" to="Иже"/>
	<element from="Й" to="ИЖЕ"/>
	<element from="к" to="Како"/>
	<element from="К" to="КАКО"/>
	<element from="л" to="Люди"/>
	<element from="Л" to="ЛЮДИ"/>
	<element from="м" to="Мыслите"/>
	<element from="М" to="МЫСЛИТЕ"/>
	<element from="н" to="Наш"/>
	<element from="Н" to="НАШ"/>
	<element from="о" to="Он"/>
	<element from="О" to="ОН"/>
	<element from="п" to="Покой"/>
	<element from="П" to="ПОКОЙ"/>
	<element from="р" to="Рцы"/>
	<element from="Р" to="РЦЫ"/>
	<element from="с" to="Слово"/>
	<element from="С" to="СЛОВО"/>
	<element from="т" to="Твердо"/>
	<element from="Т" to="ТВЕРДО"/>
	<element from="у" to="Ук"/>
	<element from="У" to="УК"/>
	<element from="ф" to="Ферт"/>
	<element from="Ф" to="ФЕРТ"/>
	<element from="х" to="Херъ"/>
	<element from="Х" to="ХЕРЪ"/>
	<element from="ц" to="Ци"/>
	<element from="Ц" to="ЦИ"/>
	<element from="ч" to="Червь"/>
	<element from="Ч" to="ЧЕРВЬ"/>
	<element from="ш" to="Ша"/>
	<element from="Ш" to="ША"/>
	<element from="щ" to="Шта"/>
	<element from="Щ" to="ШТА"/>
	<element from="ь" to="Ер"/>
	<element from="Ь" to="ЕР"/>
	<element from="ы" to="Еры"/>
	<element from="Ы" to="ЕРЫ"/>
	<element from="ъ" to="Ерь"/>
	<element from="Ъ" to="ЕРЬ"/>
	<element from="э" to="Еси'"/>
	<element from="Э" to="ЕСИ'"/>
	<element from="ю" to="Ук'"/>
	<element from="Ю" to="УК'"/>
	<element from="я" to="Аз'"/>
	<element from="Я" to="АЗ'"/>
</Transliteration>
